# define column names for user table
:user_attributes: &user_attributes
  :user_class: User
  :first_name: :first_name
  :last_name: :last_name
  :username: :username
  :email: :email
  :uid: :fb_uid
  :access_token: :fb_token
  :password: :password
  :password_confirmation: :password_confirmation
  :is_ghost: :is_ghost

:environment:
  :app_id: 306722849409928
  :app_secret: 1a2e7f4b54ea6166e5e14a906fa2f91a
  :redirect_url: http://localhost:4567/facebook
  :permissions:
    - email
    - publish_stream
  :user_attributes:
    <<: *user_attributes
